_target_: src.models.predictors.SpatialHamiltonianPredictor
name: spatial_hamiltonian
latent_channels: ${model.latent_channels}
action_dim: ${env.action_dim}
action_embedding_dim: ${model.action_embedding_dim}
action_frames: ${model.encoder_frames}
hidden_channels: ${model.hidden_channels}
context_length: ${model.context_length}
spatial_size: ${model.spatial_size}
integration_method: ${model.integration_method}
dt: ${model.predictor_dt}
damping_init: ${model.damping_init}
