name: oscillator
state_dim: 2
action_dim: 3

params: # following hamiltonian generative network paper
  m: 0.5
  k: 2.0
  c: 0.1

variable_params:
  c: [0.1, 1.0]

observation_noise_std: 0.1

init_state_range: [-1.8, 1.8]
