name: pendulum
state_dim: 2
action_dim: 3

params:
  m: 1.0
  L: 1.0
  g: 9.81
  c: 0.1

variable_params:
  c: [0.05, 0.5]

observation_noise_std: 0.1

init_state_range:
  - [-3.14, 3.14]   # theta
  - [-2.0, 2.0]     # omega
